### ISSUE TITLE
Switch xhr for corslite

### ISSUE THREAD

**Issue by freenerd** [mapbox/leaflet-mapmatch#3]
In Mapbox.js we use https://github.com/mapbox/corslite for ajax requests. Since Mapbox.js is a dependency of this leaflet plugin here anyways, we should also use corslite here.

**Comment by planemad** [comment]
@freenerd are there `POST` requests in corslite? It mentions only `GET`

**Comment by freenerd** [comment]
@planemad ah crap, I forgot. right. i think we'll stay with xhr then, since it seems most lightweight.
